### ISSUE TITLE
Unable to play to multiple Speakers in a group / Stereo Pair

### ISSUE THREAD

**Issue by prolife86** [simojenki/bonob#156]
Hi!

I have 3 speakers, 2 are in a Group / Stereo Pair.
In the Sonos App, and Spotifiy, when I play something to the "Keuken Beneden" group, i plays via both speakers.
But via Symfonium -> Navidrome and Bonob, I see the speakers as individual ie. 3 devices,but not the group.

Bonob:
![image](https://user-images.githubusercontent.com/49482721/229570551-70ccf992-46f8-49cb-8e29-fdfd93f2bc24.png)
Symfonium App:
![image](https://user-images.githubusercontent.com/49482721/229572067-02e7a6f2-9c4d-48cc-b4b5-98a5a1ab977f.png)
Sonos App:
![image](https://user-images.githubusercontent.com/49482721/229572139-3db4cb40-0f0d-4e78-a340-8e63232fdbd7.png)

Have I set it up wrongly, or is this not possible with Bonob / Navidrome / Symfonium?

**Comment by simojenki** [comment]
Bonob/navidrome don't really have any concept of the speakers themselves, or whether they are in pairs.
The only time bonob knows of the devices is when registering itself with the device.

When a track is being played that is between the app and the devices.

I suspect the issue is more with symfonium than bonob
